
# 🔒 Dependabot configuration for automated security updates
# This ensures all dependencies are kept up-to-date across the entire DevSecOps pipeline
# Documentation: https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # ================================================
  # ROOT PROJECT DEPENDENCIES
  # ================================================
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    assignees:
      - "msrj-xyz"
    commit-message:
      prefix: "🔒 Security"
      include: "scope"

  # ================================================
  # BACKEND NODE.JS API DEPENDENCIES  
  # ================================================
  - package-ecosystem: "npm"
    directory: "/projects/backend/nodejs-api"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:30"
    open-pull-requests-limit: 5
    assignees:
      - "msrj-xyz"
    commit-message:
      prefix: "🔒 Backend Security"
      include: "scope"

  # ================================================
  # FRONTEND REACT APP DEPENDENCIES
  # ================================================
  - package-ecosystem: "npm"
    directory: "/projects/frontend/react-app"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:00"
    open-pull-requests-limit: 5
    assignees:
      - "msrj-xyz"
    commit-message:
      prefix: "🔒 Frontend Security"
      include: "scope"

  # ================================================
  # DOCKER DEPENDENCIES
  # ================================================
  - package-ecosystem: "docker"
    directory: "/projects/backend/nodejs-api"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "09:00"
    open-pull-requests-limit: 3
    assignees:
      - "msrj-xyz"
    commit-message:
      prefix: "🐳 Docker Security"
      include: "scope"

  - package-ecosystem: "docker"
    directory: "/projects/frontend/react-app"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "09:30"
    open-pull-requests-limit: 3
    assignees:
      - "msrj-xyz"
    commit-message:
      prefix: "🐳 Docker Security"
      include: "scope"

  # ================================================
  # GITHUB ACTIONS DEPENDENCIES
  # ================================================
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "09:00"
    open-pull-requests-limit: 3
    assignees:
      - "msrj-xyz"
    commit-message:
      prefix: "🤖 GitHub Actions Security"
      include: "scope"
