# Environment Configuration Files
# These files define environment-specific variables

# Development Environment
development:
  gcp_project_id: "devsecops-portfolio-dev"
  gcp_region: "us-central1"  
  gke_cluster: "devsecops-dev-cluster"
  artifact_registry: "devsecops-dev-repo"
  environment_name: "development"
  node_count: 1
  node_type: "e2-small"
  auto_scaling: false
  min_nodes: 1
  max_nodes: 2
  disk_size: "30GB"
  disk_type: "pd-standard"
  monitoring_enabled: false
  security_level: "basic"
  backup_enabled: false
  high_availability: false
  
# Staging Environment  
staging:
  gcp_project_id: "devsecops-portfolio-staging"
  gcp_region: "us-central1"
  gke_cluster: "devsecops-staging-cluster" 
  artifact_registry: "devsecops-staging-repo"
  environment_name: "staging"
  node_count: 2
  node_type: "e2-standard-2"
  auto_scaling: true
  min_nodes: 1
  max_nodes: 5
  disk_size: "50GB"
  disk_type: "pd-ssd"
  monitoring_enabled: true
  security_level: "enhanced"
  backup_enabled: true
  high_availability: false

# Production Environment
production:
  gcp_project_id: "devsecops-portfolio-prod"
  gcp_region: "us-central1"
  gke_cluster: "devsecops-prod-cluster"
  artifact_registry: "devsecops-prod-repo"
  environment_name: "production"
  node_count: 3
  node_type: "e2-standard-4"
  auto_scaling: true
  min_nodes: 2
  max_nodes: 10
  disk_size: "100GB"
  disk_type: "pd-ssd"
  monitoring_enabled: true
  security_level: "maximum"
  backup_enabled: true
  high_availability: true