name: Go API CI

on:
  push:
    paths:
      - 'projects/backend/go-api/**'
  pull_request:
    paths:
      - 'projects/backend/go-api/**'

jobs:
  test:
    name: Run Go tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Run tests
        working-directory: ./projects/backend/go-api
        run: |
          go version
          go test -v ./... 2>&1 | tee test-output.txt

      - name: Upload test output
        uses: actions/upload-artifact@v4
        with:
          name: go-api-test-output
          path: projects/backend/go-api/test-output.txt
