name: Next.js CI

permissions:
  contents: read
  packages: write
  id-token: write

on:
  push:
    paths:
      - 'projects/frontend/nextjs-app/**'
  pull_request:
    paths:
      - 'projects/frontend/nextjs-app/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install
        working-directory: ./projects/frontend/nextjs-app
        # Use npm ci when a lockfile exists, otherwise fall back to npm install so CI doesn't fail
        run: npm ci || npm install
      - name: Lint
        working-directory: ./projects/frontend/nextjs-app
        run: npm run lint || true
      - name: Test
        working-directory: ./projects/frontend/nextjs-app
        run: npm run test || true
      - name: Build
        working-directory: ./projects/frontend/nextjs-app
        run: npm run build

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./projects/frontend/nextjs-app
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/nextjs-app:${{ github.sha }}

      - name: Trivy scan pushed image
        # use 'master' to follow other workflows in this repo; pin to a released tag when possible
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ghcr.io/${{ github.repository_owner }}/nextjs-app:${{ github.sha }}
          format: json
          output: projects/frontend/nextjs-app/reports/trivy-nextjs.json

      - name: Run Semgrep SAST
        # pin to a recent stable release to avoid 'unable to find version' resolution errors
        uses: returntocorp/semgrep-action@v1.25.0
        with:
          config: auto
        continue-on-error: true

      - name: NPM Audit (report)
        working-directory: ./projects/frontend/nextjs-app
        run: |
          mkdir -p reports || true
          npm audit --json > reports/npm-audit-nextjs.json || true

      - name: Upload security reports
        uses: actions/upload-artifact@v4
        with:
          name: nextjs-security-reports-${{ github.run_number }}
          path: |
            projects/frontend/nextjs-app/reports/
            projects/frontend/nextjs-app/semgrep-results.json
