name: Python API CI

on:
  push:
    paths:
      - 'projects/backend/python-api/**'
  pull_request:
    paths:
      - 'projects/backend/python-api/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install deps
        working-directory: ./projects/backend/python-api
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        working-directory: ./projects/backend/python-api
        run: |
          pytest -q
